//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public string InstitutionCode { get; set; }
        public string BranchStationCode { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public string ShortCode { get; set; }
        public string CentralSLCode { get; set; }
        public Nullable<bool> isclearingCenter { get; set; }
        public string CentralDrSLCode { get; set; }
        public string CentralCrSLCode { get; set; }
    }
}
